[[http]]
# Name of the HTTP server, used for display purposes only.
name = "relay-http"

# TCP address to bind to, for HTTP server.
bind-addr = "0.0.0.0:9096"

# Array of InfluxDB instances to use as backends for Relay.
output = [
    { name="influxdb1", location="http://influxdb-relay-docker_influxdb_1:8086/write", timeout="10s" },
    { name="influxdb2", location="http://influxdb-relay-docker_influxdb_2:8086/write", timeout="10s" },
]